dist: bionic
language: go
sudo: false
service:
  - docker

env: GO111MODULE=on

os:
  - osx
  - linux

go:
  - 1.15.x
  - 1.16.x

git:
  depth: 1

notifications:
  email: false

before_install:
  - docker run -d -p 127.0.0.1:8000:8000 amazon/dynamodb-local

script:
  - go vet ./backend/...
  - go test ./backend/...
